#include <lcom/lcf.h>
#include <lcom/lab2.h>

#include <stdbool.h>
#include <stdint.h>

extern int counter;

int main(int argc, char *argv[]) {
  // sets the language of LCF messages (can be either EN-US or PT-PT)
  lcf_set_language("EN-US");

  // enables to log function invocations that are being "wrapped" by LCF
  // [comment this out if you don't want/need it]
  lcf_trace_calls("/home/lcom/labs/lab2/trace.txt");

  // enables to save the output of printf function calls on a file
  // [comment this out if you don't want/need it]
  lcf_log_output("/home/lcom/labs/lab2/output.txt");

  // handles control over to LCF
  // [LCF handles command line arguments and invokes the right function]
  if (lcf_start(argc, argv))
    return 1;

  // LCF clean up tasks
  // [must be the last statement before return]
  lcf_cleanup();

  return 0;
}

int(timer_test_read_config)(uint8_t timer, enum timer_status_field field) {
  
  uint8_t status;
  // read the configuration of a timer
  if(timer_get_conf(timer, &status)){
    printf("Error reading timer status/config");
    return 1;
  }

  if(timer_display_conf(timer, status, field)){
   // to display timer's config fields, or all the config 
    printf("Error displaying timer status/config");
    return 1;
  }
  
  return 0;
}

int(timer_test_time_base)(uint8_t timer, uint32_t freq) {
  //configure timer to generate a time base with a given frequency in Hz

  if(timer_set_frequency (timer, freq)){
    printf("Unable to set timer's frequency\n");
    return 1;
  }
  return 0;
}  

//handles interrupts generated by Timer
int(timer_test_int)(uint8_t time) {
  //Should invoke once per second the timer_print_elapsed_time() function, for a time interval whose duration is specified
 /* The main use for the periodic interrupt generated by Timer 0 is as a time reference that can be used to measure time.
 This requires incrementing a counter on every interrupt. Thus all timer_int_handler() needs to do is to increment a global counter variable.*/

  //1. subscrever interrupts do timer -> timer_subscribe_int(uint8_t *bit_no):
  uint8_t irq_set;
  //timer_subscribe_int used to subscribe a notification on every interrupt in the input irq_line
  if(timer_subscribe_int(&irq_set)){ //irq_set = *bit_no = BIT(hook_id); bit_no will be which bit in the bit mask will go up when this IRQ line triggers
  //return, via its input argument (*bit_no), the value that it has passed to the kernel in the third argument of sys_irqsetpolicy()
    return 1;
  }
  int ipc_status, r; //ipc_status (ipc: standard interprocess communication) and r (receive) are used to receive messages from the kernel
  message msg; //msg is a message structure used to receive notifications of hardware interrupts

  //2. 
   while( time > 0 ) {
   /* This loop waits for notifications from the kernel using the driver_receive function.
      When a notification is received, the code checks to see if it is a hardware interrupt notification.
      If it is, it checks to see if the interrupt is from the timer subscription (using the irq_set bit).
      If it is, it calls the timer_int_handler function to handle the interrupt.  */
    if ( (r = driver_receive(ANY, &msg, &ipc_status)) != 0 ) { //driver_receive -> generic interrupt handler
    /*driv_receiv é uma função q permite receber mensagens, quer de outros processos quer do kernell, incluindo notificações
      - 1st argument: end point - origem das mensagens pretendidas, usamos um valor especial que é o ANY(todas as mensagens independente da sua origem);
      - 2nd argument: endereço de uma variavel do tipo message, é inicializado por driver_receive c/ a mensagem recebida
      - 3rd argument: endereço da variavel ipc_status usado para reportar se a operação de recepção foi bem sucedida e o tipo de mensagem recebida */
      printf("driver_receive failed with: %d", r);
      //driver_receive retorna uma lista de bits, indicando quais dispositivos geraram um interrupt > essa lista é a variável msg.m_notify.interrupts
      continue;
    }
    if (is_ipc_notify(ipc_status)) { /* received notification */
      switch (_ENDPOINT_P(msg.m_source)) {
        case HARDWARE: /* hardware interrupt notification */
          if (msg.m_notify.interrupts & irq_set) { // checks if the interrupt is from the timer subscription (using the irq_set bit -> irq_set = BIT(hook_id))
            timer_int_handler(); //incrementa variavel global
            //Should invoke once per second the timer_print_elapsed_time() function, for a specified interval (time)
            if(counter%60==0){
              timer_print_elapsed_time();
              time--;
            } 
          }
          break;
      default:
        break; /* no other notifications expected: do nothing */
    }
  } else { /* received a standard message, not a notification */
 /* no standard messages expected: do nothing */
    }
  }

  if (timer_unsubscribe_int() != 0) return 1;
  return 0;

}
